# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: release
distro: xenial
sudo: false
cache: packages
addons:
  apt:
    sources:
      - sourceline: 'ppa:opencpu/jq'
    packages:
      - libjq-dev
      - libprotobuf-dev
      - libv8-3.14-dev
      - libsecret-1-dev
      - libsodium-dev
      - protobuf-compiler

os:
  - osx
  - linux

after_success:
  - test $TRAVIS_OS_NAME = "osx" && Rscript -e 'covr::codecov()'
  - test $TRAVIS_OS_NAME = "linux" && R CMD INSTALL . && Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: docs
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = "linux"
