# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
addons:
  apt:
    sources:
      - sourceline: 'ppa:opencpu/jq'
    packages:
      - libjq-dev
      - libprotobuf-dev
      - libv8-3.14-dev
      - libsecret-1-dev
      - protobuf-compiler

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::clean_site(); pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs
  on:
    branch: gh-pages
